### ISSUE TITLE
Solder the PCBs

### ISSUE THREAD

**Issue by TheJimmyNowak** [TinXsat/project-structure#22]
It's work for @fifi-fifi

**Comment by TheLastGimbus** [comment]
This could be marked as done by posting a PR containing the photo of soldered PCB

**Comment by TheJimmyNowak** [comment]
Noone asked :P

**Comment by Xornee** [comment]
Dzień dobry chciałbym się zorientować w cenie biletu na mecz Ligi Mistrzów

**Comment by TheLastGimbus** [comment]
A jaka pana interesuje

trybuna?

**Comment by miki164** [comment]
Lmao

**Comment by Xornee** [comment]
Zyleta

**Comment by TheLastGimbus** [comment]
Z kartą czy bez? 💳
