### ISSUE TITLE
Describe what's our mission

### ISSUE THREAD

**Issue by TheLastGimbus** [TinXsat/project-structure#6]
@miki164 is the CEO here, so please describe briefly what's our mission in this project

If we have many, give each one it's header if it will look nice

This issue is assigned to miki, but anyone is encouraged to add his ideas!

**Comment by TheJimmyNowak** [comment]
Well here are our mission objectives I think it's good good description of our mission.

### Measurements of atmospheric pressure and temperature with  subsequent data analysis.
Key goals:
* Measure of pressure and temperature outside the cansat.
* Radio transmission of measurements data in minimal rate one packet per second.
* Calculation of altitude based on atmospheric pressure.
### Demonstration of cansat system for rescue operations during natural disasters. 
Key goals:
* Design system that meet following requirements:
* low cost of produce
* high accuracy
* Access to information about position(GPS), altitude (barometer), temperature, acceleration
* Take photos from the thermovision and visible range camera.
* Mark on photos all obstacles (to protect rescuers) and places where people could possibly be.

Optional goals:
* Investigate fire resistant biofiber composite with which body of cansat will be build
* Pointing geographical coordinates of marked obstacles/humans.

**Comment by TheLastGimbus** [comment]
Great, make a PR that puts that into README, with "resolves #6"
